/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.view;

import br.com.senac.main.Client;

/**
 *
 * @author thiag
 */
public class CltView extends javax.swing.JFrame {

    /**
     * Creates new form CltView
     */
    public CltView() {
        initComponents();
    }

    private Client client;
    private Thread threadTest;
    private String sendText = "";
    private String ip;
    private String nome;
    private Integer port;

    public void setViewText(String text) {
        this.sendText += text + "\n";
        this.textBox.setText(this.sendText);
        this.textBox.setVisible(true);
    }

    public void setOnlineText(String[] text) {
        String listaOnline = "";
        for (int i = 1; i < text.length; i++) {
            listaOnline += text[i] + "\n";
        }
        this.cxOnlineClient.setText(listaOnline);
        this.cxOnlineClient.setVisible(true);
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenu4 = new javax.swing.JMenu();
        cxPainel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBox = new javax.swing.JTextArea();
        sendTextBox = new javax.swing.JTextField();
        sendTextButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cxOnlineClient = new javax.swing.JTextArea();
        cxDestinyId = new javax.swing.JTextField();
        titleClient = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btStartMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btSettingsMenu = new javax.swing.JMenu();

        jFrame1.setResizable(false);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quick Client");
        setResizable(false);

        cxPainel.setBackground(java.awt.SystemColor.activeCaption);

        jScrollPane1.setAutoscrolls(true);

        textBox.setBackground(new java.awt.Color(204, 204, 255));
        textBox.setColumns(20);
        textBox.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textBox.setRows(5);
        jScrollPane1.setViewportView(textBox);

        sendTextBox.setBackground(new java.awt.Color(204, 204, 255));
        sendTextBox.setText("Type here...");

        sendTextButton.setText("Enviar");
        sendTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendTextButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setAutoscrolls(true);

        cxOnlineClient.setBackground(new java.awt.Color(204, 204, 255));
        cxOnlineClient.setColumns(20);
        cxOnlineClient.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        cxOnlineClient.setRows(5);
        jScrollPane2.setViewportView(cxOnlineClient);

        cxDestinyId.setBackground(new java.awt.Color(204, 204, 255));
        cxDestinyId.setText("0");

        titleClient.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        titleClient.setForeground(new java.awt.Color(0, 51, 102));
        titleClient.setText("QUICK CHAT");
        titleClient.setAlignmentY(0.0F);

        javax.swing.GroupLayout cxPainelLayout = new javax.swing.GroupLayout(cxPainel);
        cxPainel.setLayout(cxPainelLayout);
        cxPainelLayout.setHorizontalGroup(
            cxPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cxPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cxDestinyId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(sendTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cxPainelLayout.createSequentialGroup()
                .addGroup(cxPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cxPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cxPainelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(titleClient)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cxPainelLayout.setVerticalGroup(
            cxPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cxPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleClient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cxPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cxPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDestinyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendTextBox)
                    .addComponent(sendTextButton)))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("File");

        btStartMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/image/powerIcon.png"))); // NOI18N
        btStartMenu.setText("Start");
        btStartMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btStartMenuMouseClicked(evt);
            }
        });
        btStartMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btStartMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        btSettingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/image/settingsIcon.png"))); // NOI18N
        btSettingsMenu.setText("Settings");
        btSettingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSettingsMenuMouseClicked(evt);
            }
        });
        btSettingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingsMenuActionPerformed(evt);
            }
        });
        jMenu2.add(btSettingsMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cxPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cxPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendTextButtonActionPerformed
        int identificador = 0;

        if (!this.cxDestinyId.getText().equals("")) {
            identificador = Integer.parseInt(this.cxDestinyId.getText());
        }
        this.client.sendText(identificador + "//" + this.nome + " : " + this.sendTextBox.getText());
        this.sendTextBox.setText("");
    }//GEN-LAST:event_sendTextButtonActionPerformed

    private void btSettingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingsMenuActionPerformed
    }//GEN-LAST:event_btSettingsMenuActionPerformed
    private void btStartMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartMenuActionPerformed
    }//GEN-LAST:event_btStartMenuActionPerformed
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btSettingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSettingsMenuMouseClicked
        SettingsViewTest setView = new SettingsViewTest(this, true);
        setView.setClient(this);
        setView.setVisible(true);
    }//GEN-LAST:event_btSettingsMenuMouseClicked

    private void btStartMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStartMenuMouseClicked
        this.client = new Client(this);
        this.client.setIp(this.ip);
        this.client.setPort(this.port);
        this.client.setNome(this.nome);
        this.threadTest = new Thread(this.client);
        this.threadTest.start();
    }//GEN-LAST:event_btStartMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CltView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CltView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CltView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CltView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CltView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btSettingsMenu;
    private javax.swing.JMenu btStartMenu;
    private javax.swing.JTextField cxDestinyId;
    private javax.swing.JTextArea cxOnlineClient;
    private javax.swing.JPanel cxPainel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField sendTextBox;
    private javax.swing.JButton sendTextButton;
    private javax.swing.JTextArea textBox;
    private javax.swing.JLabel titleClient;
    // End of variables declaration//GEN-END:variables
}
